### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by moosburger** [Seva-coder/Finder#12]
Hi Nikita

here is the resources zip for german. I like this app, especially for my Dad. But he doesn't understand english.
Would you pls. be so kind and add it, and push the new build?

regards
moosburger

[values-de.zip](https://github.com/Seva-coder/Finder/files/3616304/values-de.zip)

**Comment by Seva-coder** [comment]
Hi! Thanks for translation! Ok, I will include it to next release, may be tomorrow. But, unfortunately, I don't know German, and I add it "as is", without any changes.
do you mind adding you to developer list? (in menu "help")

Sevastyanov Nikita

**Comment by moosburger** [comment]
Hi,
you can provide me the app before pushing it to f-droid. So i could verify my translations. To be honest, I didn't get Android Studio to build it :-(
And yes you can add me to the developer list for the translation, but I is not necessary.

moosburger

**Comment by Seva-coder** [comment]
Hi, I included your translation to repo, it's here - https://github.com/Seva-coder/Finder/tree/master/app/src/main/res/values-de (but it not marked as a release for f-droid)
and built an apk, you can [download](https://drive.google.com/file/d/1Q2tahYXdJbgPfaOR-zuz1asCrs4HtCTi/view?usp=sharing) it. Also I fixed some extra spaces and xml-tags

**Comment by moosburger** [comment]
Hi,
found some misspellings and grammatically errors. Will fix it in the next days.
Is possible in git to commit with limited rights only this files?

**Comment by Seva-coder** [comment]
I think you can use this github feature, it described here - https://help.github.com/en/articles/editing-files-in-another-users-repository
Is that what you asked? of course, i will accept your edits

**Comment by Seva-coder** [comment]
I added your translation to new release (v1.8), thanks again! small changes were needed to escape quotes and to complete xml. Also I added an icon for new androids.
Now waiting when F-Droid build it and publish...
