### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by alekksander** [Seva-coder/Finder#18]
are You open for translations? i could translate into my native (PL), just please give some instructions

**Comment by Atrate** [comment]
You have to create a folder named **values-pl** in https://github.com/Seva-coder/Finder/tree/master/app/src/main/res, copy the english strings from **values** and translate them

**Comment by alekksander** [comment]
i think i've done it before, just didn't assumed it's that easy here too :) thanks for explaining. will get to work soon

**Comment by Atrate** [comment]
@alekksander Are you working on it or do you want me to take over?

**Comment by alekksander** [comment]
@Atrate hi. with my memory i completely forgot this one isn't finished yet. over half is done, Youre free to verify and complete it further. thanks!
https://send.firefox.com/download/d19e699ae4345694/#sL2waMDz6as2CZ945z9Jdw
