### ISSUE TITLE
Open SMS activity toasts a message saying the SMS permission wasn't accepts, which isn't true.

### ISSUE THREAD

**Issue by realrufans** [Seva-coder/Finder#2]
#### Expected behavior

I expect it to recognise that the SMS permission was accepted. 

#### Actual behavior

Open SMS activity toasts a message saying the SMS permission wasn't accepted, which isn't true.

#### How to reproduce

* launch the app, accept the permissions
* Navigate to open SMS tab
* watch the page not function (it will toast a message  saying the permission wasn't granted.).

##### Browser/App version:
Finder v1.5 

##### Operating system:
Android 0

#### Recording Of The Bug

![MNML-May31-0440-1559317335089.gif](https://cdn.steemitimages.com/DQmbfK73Xsukt1t8zJRZB3gBhmCjgmxPPe45jARGMgFa92x/MNML-May31-0440-1559317335089.gif)

**Comment by Seva-coder** [comment]
@realrufans yes, it was a bug. Oreo have more strict permission check, and I forgot to add "READ_SMS" at start. But on older version of android it works. Now it will be fixed.
Moreover, Oreo itself have an important bug, which is expressed in necessity of "READ_PHONE_STARE" permission to send SMS! I also add this case (only for 8.0, 26 api) (discussed here - https://issuetracker.google.com/issues/66979952)
thanks for testing)

**Comment by Seva-coder** [comment]
fixed in v1.6

**Comment by realrufans** [comment]
Thanks
