### ISSUE TITLE
[Feature] Report altitude

### ISSUE THREAD

**Issue by Atrate** [Seva-coder/Finder#27]
It would be nice if the app also reported the altitude when grabbing GPS coords.

**Comment by Seva-coder** [comment]
but it send altitude, when location contains it...
As I understand from android specs, if gps location is available it must contain only latitude and longitude. All other data (velocity, altitude etc) may be absent.
maybe there was a bad GPS signal?

**Comment by Seva-coder** [comment]
this works here:
https://github.com/Seva-coder/Finder/blob/e8e592ff43859e01fb23d4ba9e5d5a4cfdb0c57d/app/src/main/java/ru/seva/finder/GpsSearch.java#L76

**Comment by Atrate** [comment]
Oh, my bad, probably just had bad GPS reception.

Thanks!
