### ISSUE TITLE
[Feature] User-friendly SMS Responses

### ISSUE THREAD

**Issue by andybiss** [Seva-coder/Finder#32]
The current format of SMS responses are useful when viewing once using the app to see a map view. However, if a user wants to view a geo-location a second time, or navigate to that location, they would have to manually enter this information into another application.

It may be useful to consider providing an OSM or Google Maps link to the location being sent by an SMS response so a user can easily view this location using another app or navigate there if they choose to do so.

**Comment by Atrate** [comment]
You can click on History to display coordinates in SMSes again, but I agree that having an OSM link embedded in the SMS could be a nice idea too

**Comment by andybiss** [comment]
> You can click on History to display coordinates in SMSes again, but I agree that having an OSM link embedded in the SMS could be a nice idea too

I decided to make a fork and work on this myself. I will create a PR if a contributor or owner agrees with the idea. Thanks for the input

**Comment by Seva-coder** [comment]
I agree - link to OSM in the end of SMS is good idea. OSM support short links, and I saw ready to use algorithm to create such links  in OSMand (it also open sourse). It was in utils.java or something similar.
I can add this feature in v2.1 (also I created a button to add new numbers from contacts, via intent without new permission)

**Comment by Seva-coder** [comment]
added short link to OSM (sms have enough length for it), "magic" math from osmand helped with this feature. [commit](https://github.com/Seva-coder/Finder/commit/29834d96dcbb35e5a7c7d9741f1d5a6112e9b643)
now sms looks like that:
`lat:55.99490000 lon:60.50780000 alt:5 m vel:0.00 km/h az:0 acc:20
https://osm.org/go/2N9ELwPe--?m
 bat:77%
`
(place from app's icon :)
mark it as a release for f-droid?

**Comment by Seva-coder** [comment]
ok
release created (v2.1)

**Comment by PinkDev1** [comment]
I have version 2.2 from f-droid and message responses from _wifi search_ don't have this pretty format. In fact, I think message responses from _wifi search_ don't have coordinates at all.

**Comment by Seva-coder** [comment]
Yes, "wifi response" don't have direct coordinates (lat/lon), it contain only list with mac's of surrounding nets and mobile net data. I made this, because to get location from such data we need Internet connection (to made http-request to google api, which return approximate lat/lon). It supposed, that mobile phone which answering to request does not have Internet connection at this moment. So, this operation need to be made on requesting phone (with internet).
Of course, we can check connection on answering phone, and if it has, append usual coordinates, but it will complicate the search algorithm...

**Comment by PinkDev1** [comment]
Have you considered logging these coordinates on the requesting phone?

**Comment by Seva-coder** [comment]
Yes - this app on requesting phone get direct coordinates from api, then location recorded to "history" database (like a usual gps-coordinates, except some fields like speed etc)
What happened, this feature does not work?

**Comment by PinkDev1** [comment]
Oh silly me, I didn't notice that. 
Well then, I guess you can close this issue ^^

**Comment by Seva-coder** [comment]
ok)
if you find something strange - ask me)
