### ISSUE TITLE
Feature request : sending a SMS to make the phone ring

### ISSUE THREAD

**Issue by tarbib** [Seva-coder/Finder#35]
Hello,

My phone is usually on silent mode and it happens that I have to look for it. I was wondering if it could be feasible to request the phone to ring bypassing the silent/vibrate mode?

Cheers

**Comment by Seva-coder** [comment]
Hello!

amazing coincidence! Right now I'm developing this function)
It will also work on an incoming message - disables silent mode and turns on the default call (possibly turning the volume to ~ 90%). It is planned to stop ringing by clicking on a notification

**Comment by tarbib** [comment]
Incredible ! Please let me know if you need a beta tester !

**Comment by Seva-coder** [comment]
release of v2.3 created, tested on api 17, 23 - works fine. Now app can enable sound (if it muted) and play default ringtone. User can stop playing clicking on notification, or ringtone stops automatically, by timer (playing time also can be changed in settings).
Now fdroid will build it, sometimes it take some days... If you find bug - report) I will try to fix it

**Comment by tarbib** [comment]
Awesome @Seva-coder ! Can't wait to have it on F-droid and test it :)

**Comment by Seva-coder** [comment]
@tarbib , seems like f-droid have some problems with update - all apps in "recent builds" have note in log - "could not bring up vm 'builder_default'". They know about this bug, but it yet not fixed. List is [here](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500)
I can send you my .apk, but it singned by my key (not f-droid), so it can't "update" old version, installed from f-droid. Old should be uninstalled, then installed 2.3

**Comment by Seva-coder** [comment]
f-droid [compiled](https://f-droid.org/wiki/page/ru.seva.finder/lastbuild_14) our app - at soon updated version will be available in store

**Comment by tarbib** [comment]
@Seva-coder good news! I'll check later again if I get the update on f-droid.

**Comment by Seva-coder** [comment]
They said, that updates in their official app usually faster then website, so new version may be already available via their app (I can`t check because Finder is installed on my phone, and f-droid app don`t show real current version. I will check it on emulator, but only in the evening).

6 июля 2020 г. 10:07:55 GMT+03:00, tarbib <notifications@github.com> пишет:

**Comment by Seva-coder** [comment]
this moment has come - latest version (2.3) of Finder is available on f-droid! (on both website and client)
it happened after short [dialog](https://gitlab.com/fdroid/fdroiddata/-/issues/2097) on their gitlab :)

**Comment by tarbib** [comment]
I updated :+1: 
First try, I noticed that the app autostart was disabled, so I did not have any reactions when sending the ringing command.
Second try, I enabled back autostart, kept the app open, when I sent the command it displayed a notification from finder but it did not ring (I was in silent mode for testing purpose).
Phone : Xiaomi Redmi 6

**Comment by Seva-coder** [comment]
OK, the problem may be in "change don't disturb" permission - try to change ring command in app settings (then you can set old value, this is for triggering change event in app), app will open system permissions window to allow user enable this mode. Enable checbox, and after this ringing should work...
Thanks for testing! I will try to change settings logic, to make it more clear for user

8 июля 2020 г. 9:20:15 GMT+03:00, tarbib <notifications@github.com> пишет:

**Comment by tarbib** [comment]
@Seva-coder it worked by giving the do not disturb permission!! Thank you !!

**Comment by Seva-coder** [comment]
thank you too!
in next v2.4 I will add "don't disturb permission" check to main activity, and it will check this permission in case of enabled "respond to request" checkbox
