### ISSUE TITLE
Error to send email info GPS

### ISSUE THREAD

**Issue by Khahory** [Seva-coder/Finder#40]
I have a Samsung A10, android 10. I can't get the GPS info when I run the command, I'm sure it has to work with the configuration you have and the phone number because it worked for me when I got the Wi-Fi information (a little weird I got  )

**Comment by Seva-coder** [comment]
perhaps this is due new restrictions to getting location in background in new android. I will try to fix it in new version (i think, that using "foreground services" instead usual will solve this problem)

**Comment by Khahory** [comment]
I see, I also sent the message while I had the app open on my cell phone.  I'll wait for the update, in my house we will be 3 that we will use it

**Comment by Seva-coder** [comment]
Another question - is the gps enabled in the phone settings? (on the responding phone)
if not, then to turn it on automatically, you must execute the command via [ADB:](https://github.com/Seva-coder/Finder#activate-location-automatically)
`adb shell pm grant ru.seva.finder android.permission.WRITE_SECURE_SETTINGS`

**Comment by Khahory** [comment]
Enable all permissions for the application from my cell phone, but not from ADB, is this a mandatory step?

**Comment by Khahory** [comment]
I tried but it didn't work, to be sure, I did it connected to the pc and debugger activated on the cell phone, even so it didn't send any coordinates.

![toast gps](https://i.ibb.co/qJHhnTw/Whats-App-Image-2020-09-08-at-4-29-58-PM.jpg)

The message says: SMS process failed, message would not carry coordinates, this happened when I tried to send manual coordinates, but later it showed another toast: Sending gps, but in messaging it was never sent

**Comment by Seva-coder** [comment]
I do not understand, the application on the answering phone does not send sms at all? Or SMS answer comes but is not recognized as answer for Finder?
possible variants of valid SMS-answer (for gps-request) are:
```
lat:46.34723500 lon:-9.77665667 alt:0 m vel:0.00 km/h az:0 acc:20
ts:1599912561000
https://osm.org/go/eoNU5Eot--?m
bat:100%
```

or 
```
gps not enabled
bat:100%
```

or
```
unable get location
bat:100%
```

**Comment by Khahory** [comment]
Finder recognizes the code to respond to the GPS request, the problem is that it does not respond, it only recognizes the code.

**Comment by Khahory** [comment]
Work in Android 10, Samsung A20
